server:
    port: 7070
spring:
    application:
        name: msv-kafka-producer
        version: "@project.version@"
    banner:
        location: classpath:banner/banner-prod.txt
    profiles:
        active: prod
    #  cloud:
    #    config:
    #      uri: ${CONFIG_SERVER:http://localhost:8888}
    #      fail-fast: true
    datasource:
        url: jdbc:postgresql://localhost:5432/Azure
        username: postgres
        password: Sgr9cl4v3s
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    output:
        ansi:
            enabled: ALWAYS
    kafka:
        topics:
            customerNotification: customer-notification
        producer:
            bootstrap-servers: ${HOST_PRODUCER:localhost:9092}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        properties:
            schema.registry.url: http://localhost:8081
logging:
    level:
        root: INFO